//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using forms.Repositories.Models;

//#nullable disable

//namespace FormDbContext.Migrations
//{
//    [DbContext(typeof(EstiKpracticumContext))]
//    [Migration("20230208142354_continue")]
//    partial class @continue
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "7.0.2")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("forms.Repositories.Models.Child", b =>
//                {
//                    b.Property<int>("ChildId")
//                        .HasColumnType("int")
//                        .HasColumnName("childId");

//                    b.Property<DateTime>("ChildDateBorn")
//                        .HasColumnType("date")
//                        .HasColumnName("childDateBorn");

//                    b.Property<string>("ChildName")
//                        .IsRequired()
//                        .HasMaxLength(20)
//                        .HasColumnType("nvarchar(20)")
//                        .HasColumnName("childName");

//                    b.Property<string>("ChildTz")
//                        .IsRequired()
//                        .HasMaxLength(9)
//                        .HasColumnType("nvarchar(9)");

//                    b.Property<string>("ParentTz")
//                        .IsRequired()
//                        .HasMaxLength(9)
//                        .HasColumnType("nvarchar(9)");

//                    b.HasKey("ChildId");

//                    b.ToTable("child", (string)null);
//                });

//            modelBuilder.Entity("forms.Repositories.Models.User", b =>
//                {
//                    b.Property<int>("UserId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("userId");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

//                    b.Property<DateTime>("DateBorn")
//                        .HasColumnType("date")
//                        .HasColumnName("dateBorn");

//                    b.Property<string>("FirstName")
//                        .IsRequired()
//                        .HasMaxLength(20)
//                        .HasColumnType("nvarchar(20)")
//                        .HasColumnName("firstName");

//                    b.Property<string>("Hmo")
//                        .IsRequired()
//                        .HasMaxLength(20)
//                        .HasColumnType("nvarchar(20)")
//                        .HasColumnName("hmo");

//                    b.Property<string>("LastName")
//                        .IsRequired()
//                        .HasMaxLength(20)
//                        .HasColumnType("nvarchar(20)")
//                        .HasColumnName("lastName");

//                    b.Property<string>("MaleOrFemale")
//                        .IsRequired()
//                        .HasMaxLength(20)
//                        .HasColumnType("nvarchar(20)")
//                        .HasColumnName("maleOrFemale");

//                    b.Property<string>("Tz")
//                        .IsRequired()
//                        .HasMaxLength(9)
//                        .HasColumnType("nvarchar(9)")
//                        .HasColumnName("tz");

//                    b.HasKey("UserId");

//                    b.ToTable("user", (string)null);
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
